FROM registry.eldri.ch/defn/home:update1

RUN sudo apt-get update && sudo apt-get upgrade -y

RUN make update

RUN make upgrade

RUN make install

COPY service /service
RUN sudo chmod 755 /service

RUN sudo curl -sSL https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.tgz | (cd /usr/local/bin && sudo tar xvfz -)
