FROM defn/home:home

ARG HOMEBOOT
ARG NEWUSER

ENV HOMEBOOT=$HOMEBOOT
ENV NEWUSER=$NEWUSER

USER root

RUN usermod -l $NEWUSER $HOMEBOOT
RUN id -a $NEWUSER
RUN echo "$NEWUSER ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers

USER $NEWUSER

COPY service /service
RUN sudo chmod 755 /service
