FROM defn/python

USER root

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common wget man figlet make

RUN install -d -o app -m 0700 /j

COPY etc/chunky.flf etc/broadway.flf /j/

#
USER app
#

RUN git clone https://github.com/asdf-vm/asdf.git /app/src/.asdf --branch v0.8.0
