#!/usr/bin/env bash

function main {
  case "$1" in

  cloudflared)
    shift
    cd
    cp /efs/bin/cloudflared .
    chmod 755 cloudflared

    origin=localhost
    if grep sshd /etc/hosts; then
      origin=sshd
    fi
    export TUNNEL_LB_POOL="${1}" TUNNEL_URL=ssh://${origin}:2222 TUNNEL_HOSTNAME="${1}" TUNNEL_ORIGIN_CERT="/efs/cloudflare/cert-${1}.pem"
    exec ./cloudflared tunnel --no-autoupdate
    ;;

  sshd)
    shift
    env | grep ^AWS_ | sort | sudo tee /etc/aws.env > /dev/null
    echo TrustedUserCAKeys /efs/ssh/trusted-user-ca-keys${1:+-${1}}.pem | tee -a /etc/ssh/sshd_config >/dev/null
    exec /tini -- /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o Port=2222 -e
    ;;

  esac
}

main "$@"
