FROM registry.eldri.ch/defn/home:os

ARG HOMEDIR=https://github.com/amanibhavam/homedir
ARG DOTFILES=https://github.com/amanibhavam/dotfiles

ENV PATH=/app/src/.asdf/bin:/app/src/.asdf/shims:/home/linuxbrew/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN git clone $HOMEDIR homedir \
    && mv homedir/.git . \
    && rm -rf homedir \
    && git reset --hard

RUN git clone $DOTFILES /app/src/.dotfiles

RUN make update \
    && make upgrade
