FROM defn/home

ARG HOMEDIR=https://github.com/destructuring/homedir
ARG DOTFILES=https://github.com/destructuring/dotfiles

RUN git clone $HOMEDIR \
    && mv homedir/.git . \
    && git reset --hard \
    && git submodule update --init \
    && rm -rf homedir

RUN git clone $DOTFILES /app/src/.dotfiles \
    && git submodule update --init

RUN sudo chown app:app /app/src/.cache \
    && ln -nfs .dotfiles/Makefile . \
    && make

RUN rm -rf main.py tests
