#!/usr/bin/env bash

function main {
  if [[ -S /docker.sock ]]; then
    sudo mkdir -p /var/run
    local gid="$(stat -c '%g' /docker.sock)"
    local gname="$(getent group "$gid" | cut -d: -f1)"

    if [[ -z "${gname}" ]]; then
      gname="appdocker"
      sudo /usr/sbin/groupadd -g "${gid}" "${gname}"
    fi

    sudo /usr/sbin/usermod -a -G "${gname}" app

    sudo ln -nfs /docker.sock /var/run/docker.sock
  fi

  case "${1:-}" in
    sshd)
      exec sudo -u app /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o Port=2222 -e
      ;;
    *)
      if [[ "$#" == 0 ]]; then
        set -- bash
      fi
      source /app/venv/bin/activate
      exec sudo -u app -i "$@"
      ;;
  esac

  return $?
}

main "$@"
