#!/usr/bin/env bash

function main {
  sudo chown app:app ./.git ./.git/modules ./.git/modules/.asdf ./.git/modules/.asdf/plugins ./.asdf/plugins ./.cache/pip/http/a/1 ./.cache/pip/http/a/1/9 ./.cache/pip/http/a/1/9/5

  if [[ -S /docker.sock ]]; then
    sudo mkdir -p /var/run
    local gid="$(stat -c '%g' /docker.sock)"
    local gname="$(getent group "$gid" | cut -d: -f1)"

    if [[ -z "${gname}" ]]; then
      gname="appdocker"
      sudo /usr/sbin/groupadd -g "${gid}" "${gname}"
    fi

    sudo /usr/sbin/usermod -a -G "${gname}" app

    sudo ln -nfs /docker.sock /var/run/docker.sock
  fi

  if [[ "$#" -gt 0 ]]; then
    source /app/venv/bin/activate
    exec sudo -u app -i "$@"
    return $?
  fi

  exec sudo -u app /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o Port=2222 -e
}

main "$@"
