#!/usr/bin/env bash

function argo-tunnel {
  while true; do
    cloudflared tunnel --hostname "$1" --url ssh://"$2":2222 --origincert /efs/config/cloudflared/cert.pem --no-chunked-encoding
    sleep 5
  done
}

function argo-proxy {
  while true; do
    cloudflared tunnel --origincert /efs/config/cloudflared/cert.pem --no-chunked-encoding --hostname "$@"
    sleep 5
  done
}

function irssi-screen {
  mkdir -p /home/ubuntu/.irssi
  ln -nfs /efs/config/irssi/config /home/ubuntu/.irssi/config

  screen -S irssi -d -m irssi -c EFNet "$@" &

  exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o Port=2222 -e
}

function sshd-server {
  env -u PATH -u DEBIAN_FRONTEND -u USER -u HOME env | egrep -v '^(PWD|SHLVL|_)=' > .env

  if [[ -S /docker.sock ]]; then
    sudo ln -nfs /docker.sock /var/run/docker.sock
    sudo chown ubuntu:ubuntu /docker.sock
  fi

  exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o Port=2222 -e
}

function main {
  set -x

  cd /home/ubuntu

  case "${1:-}" in
    argo-tunnel)
      shift
      if [[ -z "${2:-}" ]]; then set -- "$@" home; fi
      argo-tunnel "$@"
      ;;
    argo-proxy)
      shift
      argo-proxy "$@"
      ;;
    irssi-screen)
      shift
      irssi-screen "$@"
      ;;
    nginx)
      shift
      rm -rf /var/www/html
      git clone https://github.com/gabrielecirulli/2048 /var/www/html
      exec nginx -g "daemon off;" "$@"
      ;;
    teleport)
      shift
      exec sudo teleport start "$@"
      ;;
    *)
      shift
      sshd-server "$@"
      ;;
  esac
}

main "$@"

