kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  image: kindest/node:v1.18.2
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
    protocol: TCP
  - containerPort: 1194
    hostPort: 1194
    protocol: TCP
  extraMounts:
  - hostPath: /data
    containerPath: /data
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  image: kindest/node:v1.18.2
  extraPortMappings:
  extraMounts:
  - hostPath: /data
    containerPath: /data
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  image: kindest/node:v1.18.2
  extraPortMappings:
  extraMounts:
  - hostPath: /data
    containerPath: /data
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    certSANs:
    - localhost
    - 127.0.0.1
    - kubernetes
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - kind
    - 172.18.0.1
    - host.docker.internal
