kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "10.70.0.0/16"
  serviceSubnet: "10.71.0.0/16"
nodes:
- role: worker
  image: kindest/node:v1.18.2
  extraMounts:
  - hostPath: /data
    containerPath: /data
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  image: kindest/node:v1.18.2
  extraMounts:
  - hostPath: /data
    containerPath: /data
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  image: kindest/node:v1.18.2
  extraMounts:
  - hostPath: /data
    containerPath: /data
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: control-plane
  image: kindest/node:v1.18.2
  extraMounts:
  - hostPath: /data
    containerPath: /data
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
    protocol: TCP
  - containerPort: 1194
    hostPort: 1194
    protocol: TCP
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    certSANs:
    - localhost
    - 127.0.0.1
    - kubernetes
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - kind
    - 172.18.0.1
    - host.docker.internal
