#!/usr/bin/env bash

function main {
  if [[ "$(whoami)" == "root" ]]; then
    exec sudo -H -i -u app "$0" "$@"
    return $?
  fi

  if type -P yum; then
    sudo yum install -y jq aws-cli # for basic aws ops

    sudo yum install -y openssh-clients # for plain amazon linux
    sudo yum install -y unzip wget git rsync bind-utils
    sudo yum install -y amazon-efs-utils
    sudo yum install -y python3
    sudo yum install -y gnupg2 yum-utils # for tailscale repo
    sudo yum upgrade -y
  elif type -P apt-get; then
    sudo apt-get update
    sudo apt-get install -y jq awscli

    sudo apt-get install -y unzip wget git rsync bind9-utils
    sudo apt-get install -y python3 python3-venv
    sudo apt-get install -y docker.io
    sudo usermod -G docker app
  fi

  sudo curl -sSL -o /usr/local/bin/powerline-go \
    https://github.com/justjanne/powerline-go/releases/download/v1.17.0/powerline-go-linux-amd64
  sudo chmod 755 /usr/local/bin/powerline-go

  sudo curl -sSL -o /usr/local/bin/docker-compose \
    https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64
  sudo chmod 755 /usr/local/bin/docker-compose

  sudo install -d -o app -g app -m 0700 ~app/.ssh
  curl -s https://api.github.com/users/jojomomojo/keys | jq -r '.[].key' | sudo tee -a ~app/.ssh/authorized_keys
}

main "$@"
