#!/usr/bin/env bash

function main {
  if [[ "$(whoami)" == "root" ]]; then
    exec sudo -H -i -u app "$0" "$@"
    return $?
  fi

  set -x

  sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
}

main "$@"
