#!/usr/bin/env bash

function main {
  if [[ "$(whoami)" == "root" ]]; then
    exec sudo -H -i -u app "$0" "$@"
    return $?
  fi

  set -x

  curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash
}

main "$@"
