#!/usr/bin/env bash

function main {
  if [[ "$(whoami)" == "root" ]]; then
    exec sudo -H -i -u app "$0" "$@"
    return $?
  fi

  set -x

  curl -Ss https://my-netdata.io/kickstart.sh > /tmp/netdata.sh
  sudo bash /tmp/netdata.sh
  rm -f /tmp/netdata.sh
}

main "$@"
