#!/usr/bin/env bash

function main {
  if [[ "$(whoami)" == "root" ]]; then
    exec sudo -H -i -u app "$0" "$@"
    return $?
  fi

  set -exfu

  if curl -s 'https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg' | gpg --import; then
    if z=$(curl -s 'https://install.zerotier.com/' | gpg); then
      echo "$z" | sudo bash
    fi
  fi

  sudo systemctl stop zerotier-one
  sudo systemctl disable zerotier-one
  sudo rm -vf \
    /var/lib/zerotier-one/zerotier-one.pid \
    /var/lib/zerotier-one/authtoken.secret \
    /var/lib/zerotier-one/identity.secret \
    /var/lib/zerotier-one/identity.public \
    /var/lib/zerotier-one/zerotier-one.port
}

main "$@"
