#!/usr/bin/env bash

function main {
  if [[ "$(whoami)" == "root" ]]; then
    exec sudo -H -i -u app "$0" "$@"
    return $?
  fi

  set -exfu

  if type -P yum; then
    sudo amazon-linux-extras install kernel-ng
  fi
}

main "$@"
