#!/usr/bin/env bash

function main {
  if [[ "$(whoami)" == "root" ]]; then
    exec sudo -H -i -u app "$0" "$@"
    return $?
  fi

  set -exfu

  if type -P yum; then
    sudo amazon-linux-extras install java-openjdk11
  elif type -P apt-get; then
    sudo apt-get install -y openjdk-11-jdk
  fi
}

main "$@"
