#!/usr/bin/env bash

function main {
  if [[ "$(whoami)" == "root" ]]; then
    exec sudo -H -i -u app "$0" "$@"
    return $?
  fi

  set -exfu

  ssh -o StrictHostKeyChecking=no git@github.com true || true
  git clone https://github.com/amanibhavam/homedir
  homedir/bin/install-homedir
}

main "$@"
