#!/usr/bin/env bash

n=$1; shift

cat farcast${n}.json | jq --arg ip "$(docker inspect "$(docker-compose ps -q kuma-app-pause-${n})" | jq -r '.[] | .NetworkSettings.Networks[].IPAddress')" '. + {ip_container: $ip}' > farcast${n}tmp.json

cue export farcast.cue farcastx.cue farcast${n}.cue farcast${n}tmp.json  | yq -y '.app' | docker-compose exec -T kuma-cp-${n} kumactl apply -f -

rm -f farcast${n}tmp.json

docker-compose exec -T kuma-cp-${n} kumactl generate dataplane-token --dataplane=app | docker-compose exec -T kuma-cp-${n} tee /config/farcast${n}-app-token > /dev/null

docker-compose stop kuma-app-dp-${n} kuma-app-${n}
docker-compose rm -f kuma-app-dp-${n} kuma-app-${n}
docker-compose up -d kuma-app-dp-${n}
docker-compose up -d kuma-app-${n}

echo app${n} | docker-compose exec -T kuma-app-${n} tee /usr/share/nginx/html/index.html
