#!/usr/bin/env bash

dataplane=app
token=app

for n in $(cue export docker-compose.cue todo.cue | jq -r '.zones[]'); do
  echo app${n} | docker-compose exec -T app-${n} tee /usr/share/nginx/html/index.html

  docker-compose exec -T kuma-cp-${n} \
    kumactl generate dataplane-token --dataplane=$dataplane \
      | docker-compose exec -T kuma-cp-${n} \
          tee /config/farcast${n}-${token}-token > /dev/null
done

dataplane=kuma-ingress
token=ingress

for n in $(cue export docker-compose.cue todo.cue | jq -r '.zones[]'); do
  docker-compose exec -T kuma-cp-${n} \
    kumactl generate dataplane-token --dataplane=$dataplane \
      | docker-compose exec -T kuma-cp-${n} \
          tee /config/farcast${n}-${token}-token > /dev/null
done
