#!/usr/bin/env bash

selector=.app

for n in $(cue export docker-compose.cue todo.cue | jq -r '.zones[]'); do
  echo app${n} | docker-compose exec -T app-${n} tee /usr/share/nginx/html/index.html

  ip_container="$(docker inspect "$(docker-compose ps -q app-pause-${n})" | jq -r '.[] | .NetworkSettings.Networks[].IPAddress')"

  jq -n --arg ip "$ip_container" '{ip_container: $ip}' > farcast${n}tmp.json

  cue export farcast.cue farcastx.cue farcast${n}.cue farcast${n}tmp.json \
    | yq -y "${selector}" \
    | docker-compose exec -T kuma-remote-${n} \
        kumactl apply -f -
done

rm -f farcast*tmp.json
