#!/usr/bin/env bash

function main {
  cue export farcast.cue | yq -y '.traffic_permission' | docker-compose exec -T kuma-global kumactl apply -f -
  cue export farcast.cue | yq -y '.mesh' | docker-compose exec -T kuma-global kumactl apply -f -

  for n in $(cue export docker-compose.cue todo.cue | jq -r '.zones[]'); do
    local ip_container="$(docker inspect "$(docker-compose ps -q zerotier${n})" | jq -r '.[] | .NetworkSettings.Networks[].IPAddress')"

    jq -n --arg ip "$ip_container" '{ip_container: $ip}' > farcast${n}tmp.json

    cue export farcast.cue farcastx.cue farcast${n}.cue farcast${n}tmp.json \
      | yq -y '.zone' \
      | docker-compose exec -T kuma-global kumactl apply -f -
  done

  rm -f farcast*tmp.json
}

main "$@"
