#!/usr/bin/env bash

selector=.ingress

for n in $(cue export docker-compose.cue todo.cue | jq -r '.zones[]'); do
  cat farcast${n}.json \
    > farcast${n}tmp.json

  # meh
  cue export farcast.cue farcastx.cue farcast${n}.cue farcast${n}tmp.json \
    | yq -y "${selector}" \
    | docker-compose exec -T kuma-cp-${n} \
        kumactl apply -f -
done

rm -f farcast*tmp.json
