#!/usr/bin/env bash

function main {
  cat traffic-permission-allow-all-traffic.yaml | docker-compose exec -T kuma-global kumactl apply -f -
  cat mesh-default.yaml | docker-compose exec -T kuma-global kumactl apply -f -
  cat farcast1-zone.yaml | docker-compose exec -T kuma-global kumactl apply -f -
  cat farcast2-zone.yaml | docker-compose exec -T kuma-global kumactl apply -f -
}

main "$@"
