#!/usr/bin/env bash

function main {
  cue export farcast.cue | yq -y '.traffic_permission' | docker-compose exec -T kuma-global kumactl apply -f -
  cue export farcast.cue | yq -y '.mesh' | docker-compose exec -T kuma-global kumactl apply -f -

  for n in $(cue export docker-compose.cue  | jq -r '.zones[]'); do
    cue export farcast.cue farcastx.cue farcast${n}.cue farcast${n}.json \
      | yq -y '.zone' \
      | docker-compose exec -T kuma-global kumactl apply -f -
  done
}

main "$@"
