#!/usr/bin/env bash

set -x

useradd -m -s /bin/bash jojomomojo

chgrp app /var/run/docker.sock

chown root:root /run/sshd

exec /tini -- /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o Port=2222 -e
